version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: python.Dockerfile
      platforms:
        - "linux/amd64"
    platform: linux/amd64
    image: band:latest
    environment:
      - TZ=Asia/Seoul
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips '*' --reload --reload-dir /app
    ports:
      - "8087:8000"
    volumes:
      - ./app:/app
      - ./database.db:/app/database.db
      - ./user_data:/app/user_data
networks:
  local-network:
    driver: bridge
