# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://auth.band.us/login_page?next_url=https%3A%2F%2Fband.us%2Fhome%3Freferrer%3Dhttps%253A%252F%252Fband.us%252F")
    self.driver.set_window_size(1504, 1667)
    self.driver.find_element(By.CSS_SELECTOR, "#email_login_a > .text").click()
    self.driver.find_element(By.ID, "input_email").send_keys("ril_k")
    self.driver.find_element(By.ID, "input_email").click()
    self.driver.find_element(By.ID, "input_email").click()
    element = self.driver.find_element(By.ID, "input_email")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "input_email").send_keys("smkang0321@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".uBtn").click()
    self.driver.find_element(By.ID, "pw").click()
    self.driver.find_element(By.ID, "pw").send_keys("Rkakrnl1318#")
    self.driver.find_element(By.ID, "pw").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "pw").send_keys("cjdfyd2024!")
    self.driver.find_element(By.ID, "pw").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "code").click()
    self.driver.find_element(By.ID, "code").send_keys("8333")
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uBtn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bandCardItem:nth-child(3) .uCoverImage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cCard:nth-child(2) .postWriter").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dPostCommentMainView:nth-child(6) .cComment:nth-child(1) .name").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dPostCommentMainView:nth-child(6) .cComment:nth-child(1) .name")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "write_comment_view964").send_keys("@강성묵 안녕하세요")
    self.driver.find_element(By.CSS_SELECTOR, ".-active:nth-child(2)").click()
  
